[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.95

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 10
